version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - user-service
      - notes-service
    networks:
      - app-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=Password
      - DB_NAME=notes_app_db
      - DB_PORT=5432
      - JWT_SECRET=SecretKey
    depends_on:
      - db
    networks:
      - app-network

  notes-service:
    build:
      context: ./notes-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=Password
      - DB_NAME=notes_app_db
      - DB_PORT=5432
      - JWT_SECRET=SecretKey
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password
      - POSTGRES_DB=notes_app_db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - user-service
      - notes-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: